config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end

  root to: 'event#index'

  resources :mypages, only:[:index] do
    collection do
      get 'logout'
    end
  end

  resources :complete_pages, only: [:index]
  resources :event, only:[:index, :new, :create, :show]
  resources :article, only:[:index] 
  resources :movie, only:[:index] 
  resources :items, only:[:index] 

end

app/models/address.rb
class Address < ApplicationRecord
  validates :post_number, :prefecture_id, :city, :town, presence: true
  validates :post_number, format: { with: /\A[0-9]{3}-[0-9]{4}\z/ }
  
  belongs_to :user, optional: true
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_many :article_image, dependent: :delete_all
end

app/models/article_image.rb
class ArticleImage < ApplicationRecord

  belongs_to :article
  # mount_uploader :image, ImageUploader
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :item
end

app/models/event.rb
class Event < ApplicationRecord

  
  belongs_to :user, optional: true
  has_many :event_images, dependent: :delete_all

  accepts_nested_attributes_for :event_images, allow_destroy: true
  
end

app/models/event_image.rb
class EventImage < ApplicationRecord
  validates :image, presence: true

  belongs_to :event, optional: true
  mount_uploader :image, EventImagesUploader
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  has_many :item_image, dependent: :delete_all
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  validates :top_image, presence: true

  belongs_to :item
  # mount_uploader :image, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user, optional: true
end

app/models/move.rb
class Move < ApplicationRecord
  
  belongs_to :user, optional: true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
      {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
      {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
      {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
      {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
      {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
      {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
      {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
      {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
      {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
      {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
      {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
      {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
      {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
      {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
      {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
      {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :address, dependent: :delete

  has_many :item, dependent: :delete_all
  has_many :event, dependent: :delete_all
  has_many :move, dependent: :delete_all
  has_many :message, dependent: :delete_all

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title SmileApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_chatBtn.html.haml
.chatBtn
  =link_to "", class: "chat-link" do
    .font-block
      %p チャットで相談
      =image_tag scr="chat_image.jpg", size: "70"

app/views/shared/_footer.html.haml
.footer
  .footer-contents
    %ul.contents
      %li.content
        %h2.content-heading
          Smileについて
        %ul.footer-lists
          %li 
            =link_to "#" do
              会社概要（運営会社）
          %li 
            =link_to "#" do
              プライバシーポリシー
          %li 
            =link_to "#" do
              Smile利用規約
          %li 
            =link_to "#" do
              Smile登録規約
      %li.content
        %h2.content-heading
          Smile登録工務店
        %ul.footer-lists
          %li
            =link_to "#" do
              登録工務店一覧
          %li
            =link_to "#" do
              登録希望の工務店様へ
      %li.content
        %h2.content-heading
          Smileへの投稿&編集
        %ul.footer-lists
          %li
            =link_to new_event_path do
              ハウジングイベント投稿&編集
          %li
            =link_to "#" do
              DIY動画投稿&編集
          %li
            =link_to "#" do
              INTERIOR SHOP出品&編集
      %li.content
        %h2.content-heading
          ヘルプ＆ガイド
        %ul.footer-lists
          %li 
            =link_to "#" do
              Smileガイド
          %li
            =link_to "#" do
              利用ガイドライン
          %li
            =link_to "#" do
              お知らせ
    

app/views/shared/_header.html.haml
.header
  .header-box
    .top
      %ul.menu-box
        %li.new-account
          =link_to "#" do
            初めての方
        %li.help-link
          =link_to "#" do
            ヘルプ・お問い合わせ
    .center
      .title-box
        %ul.left-contents
          %li.title
            =link_to root_path do
              Smile
          %li.sub
            暮らしを " 楽しく" "おしゃれに"          
        -if user_signed_in?
          %ul.right-contents
            %li.right-contents__item--login
              =link_to mypages_path, class: "list-link" do
                マイページ
        -else
          %ul.right-contents
            %li.right-contents__item--login
              =link_to new_user_session_path, class: "list-link" do
                ログイン
            %li.right-contents__item--new
              =link_to new_user_registration_path, class: "list-link" do
                新規会員登録

    .bottom
      %ul.contents-box
        %li.top
          =link_to root_path do
            TOP
        %li.article
          =link_to article_index_path do
            FEATURE COLUMN
        %li.move
          =link_to movie_index_path do
            DIY MOVIE
        %li.shop
          =link_to items_path do
            INTERIOR SHOP